CREATE TABLE IF NOT EXISTS push_review_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  project_name VARCHAR(128) NOT NULL,
  author VARCHAR(128) NOT NULL DEFAULT '',
  author_identity VARCHAR(128) NOT NULL DEFAULT '',
  author_display_name VARCHAR(128) NOT NULL DEFAULT '',
  branch VARCHAR(255) NOT NULL DEFAULT '',
  commit_messages TEXT NULL,
  commits JSON NULL,
  score INT NOT NULL DEFAULT 0,
  additions INT NOT NULL DEFAULT 0,
  deletions INT NOT NULL DEFAULT 0,
  last_commit_url VARCHAR(1024) NOT NULL DEFAULT '',
  review_result TEXT NULL,
  share_token VARCHAR(128) NOT NULL DEFAULT '',
  share_token_expires_at BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_push_review_log_project_id (project_id),
  KEY idx_push_review_log_project_name (project_name),
  KEY idx_push_review_log_author (author),
  KEY idx_push_review_log_author_identity (author_identity),
  KEY idx_push_review_log_branch (branch),
  KEY idx_push_review_log_score (score),
  KEY idx_push_review_log_share_token (share_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merge_request_review_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  project_name VARCHAR(128) NOT NULL,
  author VARCHAR(128) NOT NULL DEFAULT '',
  author_identity VARCHAR(128) NOT NULL DEFAULT '',
  author_display_name VARCHAR(128) NOT NULL DEFAULT '',
  source_branch VARCHAR(255) NOT NULL DEFAULT '',
  target_branch VARCHAR(255) NOT NULL DEFAULT '',
  commit_messages TEXT NULL,
  score INT NOT NULL DEFAULT 0,
  additions INT NOT NULL DEFAULT 0,
  deletions INT NOT NULL DEFAULT 0,
  last_commit_id VARCHAR(128) NOT NULL DEFAULT '',
  url VARCHAR(1024) NOT NULL DEFAULT '',
  review_result TEXT NULL,
  share_token VARCHAR(128) NOT NULL DEFAULT '',
  share_token_expires_at BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_mr_review_log_project_id (project_id),
  KEY idx_mr_review_log_project_name (project_name),
  KEY idx_mr_review_log_author (author),
  KEY idx_mr_review_log_author_identity (author_identity),
  KEY idx_mr_review_log_source_branch (source_branch),
  KEY idx_mr_review_log_target_branch (target_branch),
  KEY idx_mr_review_log_score (score),
  KEY idx_mr_review_log_last_commit_id (last_commit_id),
  KEY idx_mr_review_log_share_token (share_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
